version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:8.12.0
        # environment:
        #   FOOD: $BAR
    # resource_class: large

references:
  # Paths
  default_workspace: &default_workspace ~/beprojs-repo
  # Cache keys
  node_cache_key: &node_cache_key node-v1-{{ checksum "package.json" }}-{{ arch }}
  # Branch filters
  feature_filter: &feature_filter
    branches:
      ignore:
        - master

commands:
  prepare_code:
    steps:
      - restore_cache:
          key: *node_cache_key
      # - run:
      #     name: update-npm
      #     command: "npm install -g npm@latest"
      - run:
          name: install truffle@5.1.7 globally
          command: npm install -g truffle@5.1.7
      - checkout
      - run:
          name: install repo's node modules
          command: npm run install
      - save_cache:
          key: *node_cache_key
          paths:
            - node_modules
jobs:
  tests:
    working_directory: *default_workspace
    executor: node
    steps:
      - prepare_code
      - run:
          name: tests
          command: npm run test

workflows:
  code-checks:
    jobs:
      - tests:
          filters: *feature_filter
