version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:8.12.0
        # environment:
        #   FOOD: $BAR
    resource_class: medium

references:
  # Paths
  default_workspace: &default_workspace ~/beprojs-repo
  # Cache keys
  node_cache_key: &node_cache_key node-v1-{{ checksum "package-lock.json" }}-{{ arch }}
  # Branch filters
  feature_filter: &feature_filter
    branches:
      ignore:
        - master

commands:
  prepare_code:
    steps:
      - checkout:
          path: *default_workspace
      - restore_cache:
          key: *node_cache_key
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - run:
          name: install truffle@5.1.7 globally
          command: sudo npm install -g --unsafe-perm=true truffle@5.1.7
      - run:
          name: install repo's node modules
          command: npm install
      - save_cache:
          key: *node_cache_key
          paths:
            - node_modules
jobs:
  tests:
    working_directory: *default_workspace
    executor: node
    steps:
      - prepare_code
      - run: mkdir ~/reports
      - run:
          name: tests
          command: npm run test
          environment:
            MOCHA_FILE: ~/reports/results.xml
          when: always
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports

workflows:
  code-checks:
    jobs:
      - tests:
          filters: *feature_filter
