name: Updated documentation

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: NPM Install
        run: npm install
        
      - name: Compile contracts
        run: npm run compile

      - name: Build documentation from source
        run: npm run docs

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          enable_jekyll: false
